import numpy as np
import matplotlib.pyplot as plt


class RandomGaussianGenerator:
    def __init__(self, seed=None):
        self.rng = np.random.default_rng(seed)

    def generate(self, size=None):
        return self.rng.normal(loc=0, scale=4, size=size)

    def __call__(self, size=None):
        return self.generate(size)


"""if __name__ == "__main__":
    generator1 = RandomGaussianGenerator(seed=42)
    
    random_numbers = generator1(size=1000000)

    plt.hist(random_numbers, bins='auto')  # Ustawienie liczby słupków na 10
    plt.xlabel('Value')
    plt.ylabel('Frequency')
    plt.title('Histogram of Random Numbers Generated by generator1')
    plt.show()"""
